# Copyright 2009  The "goconfig" Authors
#
# Use of this source code is governed by the Simplified BSD License
# that can be found in the LICENSE file.
#
# This software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied. See the License
# for more details.

include $(GOROOT)/src/Make.inc

TARG=github.com/kless/goconfig/config
GOFILES=\
	error.go\
	main.go\
	option.go\
	read.go\
	section.go\
	type.go\
	write.go\

include $(GOROOT)/src/Make.pkg

